
import zipfile
z = zipfile.ZipFile(r"C:/Users/30855/WorkBuddy/2026-09-15-16-07-08/CipherBox-1.8.1.apk")
names = z.namelist()
print("zip entries:", len(names))
print("classes.dex:", "classes.dex" in names)
print("AndroidManifest.xml:", "AndroidManifest.xml" in names)
print("assets/vault.html:", "assets/vault.html" in names)
h = z.read("assets/vault.html").decode("utf8")
print("html bytes:", len(h))
print("html complete:", h.strip().endswith("</html>"))
print("html has pinyin:", "PY_GROUPS" in h)
print("html has dup-flag:", ".dup-flag" in h)
print("html has export menu:", "exportOverlay" in h)
print("html has kdf 600k:", "KDF_ITERS_WC = 600000" in h)
print("html has lock close:", "closeAllScrims" in h)
